version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ml_project
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "9090:5432"
